import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  product: {
    width: 100,
    height: 100,
    backgroundColor: '#D1D1D1',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 50,
    borderRadius: 5,
  },
  productContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    backgroundColor: 'white',
    elevation: 5,
    padding: 10,
    borderRadius: 10,
  },
  productSection: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  cartSection: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-end',
    marginTop: 40,
  },
  cartContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: 40,
    height: 40,
    backgroundColor: "#0091F1",
    borderRadius: 50,
    marginRight: 10,
    marginTop: 10,
  },
  productCounterText: {
    position: 'absolute',
    transform: [{ translateX: -36 }, { translateY: 20 }],
    backgroundColor: '#F14100',
    width: 20,
    height: 20,
    textAlign: 'center',
    borderRadius: 50,
    color: "white",
  },
  container: {
    marginTop: 50,
    height: '100%',
    padding: 20,
  },
  title: {
    width: '100%',
    textAlign: 'center',
    fontSize: 24,
  },
  categoryListContainer: {
    marginTop: 20,
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    marginBottom: 50,
  },
  categoryContainer: {
    width: '100%',
    height: "auto",
    backgroundColor: '#E4E4E4',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    padding: 10,
    borderRadius: 10,
    elevation: 5,
  },
  image: {
    width: 80,
    height: 80,
    zIndex: 1,
    backgroundColor: 'red',
    borderRadius: 8,
  },
  categoryContainerText: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    marginLeft: 10,
  },
  categoryOptionsContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    width: 70,
  },
  categoryName: {
    fontWeight: 'bold',
    fontSize: 16,
  },
  categoryDescription: {
    fontSize: 14,
    paddingTop: 5,
    width: 180,
  },
  icon: {
    width: 25,
    height: 25,
    marginBottom: 5,
  },
  categoryContainerImage: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  leftSection: {
    display: 'flex',
    flexDirection: 'row',
  },
  modal: {
    position: "absolute",
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0,0,0,0.5)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',

  },
  modalContainer: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 10,
    width: '90%',
    elevation: 5,
  },
  modalButtons: {
    display: 'flex',
    justifyContent: 'space-around',
    flexDirection: 'row',
    marginTop: 20,
  },
  modalAcceptButton: {
    padding: 10,
    borderRadius: 10,
    backgroundColor: '#ff432a',
  },
  modalBackButton: {
    padding: 10,
    borderRadius: 10,
    borderColor: '#ff432a',
    borderWidth: 1,
  },
  inputTextArea: {
    fontStyle: 'italic',
    paddingLeft: 10,
    borderBottomWidth: 1,
    backgroundColor: '#FFFFFF',
    borderColor: '#FF4141',
    borderWidth: 1,
    borderRadius: 50,
    fontWeight: 'bold',
    height: 40,
    width: '100%',
  },
  textInputContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    marginTop: 20,
  },
  InputText: {
    marginLeft: 10,
    marginBottom: 5,
  },
  noData: {
    width: '100%',
    height: '100%',
    textAlign: 'center',
    marginTop: 200,
    fontSize: 20,
    color: "#B1B1B1",
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageButton: {
    display: 'flex',
    justifyContent: 'center',
    alignContent: 'center',
    backgroundColor: '#FF4141',
    borderRadius: 5,
    width: 200,
    marginTop: 20,
    transform: [{ translateX: 70 }],
    marginBottom: 20,
  },
  imageButtonText: {
    textAlign: 'center',
    color: '#FFFFFF',
    padding: 5,
    fontSize: 16,
  },
  editImage: {
    width: 100,
    height: 100,
    backgroundColor: 'red',
    marginBottom: 20,
    left: "50%",
    transform: [{ translateX: -50 }],
  },
  listTitle: {
    fontSize: 20,
  },
});