import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container:{
    height: '100%',
  },
  form: {
    display: 'flex',
    backgroundColor: 'white',
    height: '100%',
    padding: 20,
  },
  title: {
    textAlign: 'center',
    fontSize: 30,
    marginBottom: 20,
    borderBottomWidth: 1,
    borderColor: '#B1B1B1',
    paddingBottom: 10,
  },
  icon: {
    width: 35,
    height: 35,
    position: 'absolute',
    zIndex: 1,
    transform: [{ translateX: 5 }],
  },
  adminButton: {
    display: 'flex',
    justifyContent: 'center',
    alignContent: 'center',
    backgroundColor: '#FF4141',
    borderRadius: 50,
    width: '100%',
  },
  adminButtonText: {
    textAlign: 'center',
    color: '#FFFFFF',
    padding: 5,
    fontSize: 24,
  },
  errorMessage: {
    color: '#FF4141',
    fontSize: 12,
    textAlign: 'center',
    marginBottom: 20,
    width: '70%',
    transform: [{ translateX: 50 }, {translateY: -10}],
    borderRadius: 5,
    zIndex: -1,
  },
  inputContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 0,
    marginBottom: 10,
  },  
  inputImage: {
    backgroundColor: '#FF4141',
    width: 30,
    height: 30,
    borderRadius: 50,
    position: 'absolute',
    zIndex: 1,
    transform: [{ translateX: -165 }],
  },
  input: {
    width: '100%',
    height: 40,
    padding: 10,
    backgroundColor: '#FFFFFF',
    borderColor: '#FF4141',
    borderWidth: 1,
    borderRadius: 50,
    fontWeight: '900',
    textAlign: 'left',
    color: '#000000',
  },
  button: {
    display: 'flex',
    justifyContent: 'center',
    alignContent: 'center',
    backgroundColor: '#FF4141',
    borderRadius: 5,
    marginTop: 40,
    width: '100%',
  },
  imageButton: {
    display: 'flex',
    justifyContent: 'center',
    alignContent: 'center',
    backgroundColor: '#FF4141',
    borderRadius: 5,
    width: '60%',
    transform: [{ translateX: 70 }],
    marginBottom: 10,
  },
  buttonText: {
    textAlign: 'center',
    color: '#FFFFFF',
    padding: 5,
    fontSize: 18,
  },
  imageButtonText: {
    textAlign: 'center',
    color: '#FFFFFF',
    padding: 5,
    fontSize: 16,
  },
  inputTextArea: {
    width: '100%',
    padding: 10,
    height: 80,
    backgroundColor: '#FFFFFF',
    borderColor: '#FF4141',
    borderWidth: 1,
    borderRadius: 15,
    fontWeight: '900',
    color: '#000000',
    textAlignVertical: 'top',
    textAlign: 'left',
  },
  image: {
    width: 100,
    height: 100,
    zIndex: 1,
    transform: [{ translateX: 140 }, { translateY: 15 }],
    borderColor: "black",
    borderWidth: 2,
  }
});
